export type TransportNodeKind = "AIRPORT" | "PORT";

export type TransportNode = {
  id: string;
  kind: TransportNodeKind;
  name: string;
  label: string;
  countryIso2: string;
  latitude: number;
  longitude: number;
  keywords: string[];
};

export const TRANSPORT_NODES: TransportNode[] = [
  {
    id: "airport-abj",
    kind: "AIRPORT",
    name: "Aeroport international Felix-Houphouet-Boigny",
    label: "Abidjan, Cote d'Ivoire",
    countryIso2: "CI",
    latitude: 5.261386,
    longitude: -3.926294,
    keywords: ["abidjan", "felix", "houphouet", "airport", "aeroport", "abj"],
  },
  {
    id: "port-abidjan",
    kind: "PORT",
    name: "Port Autonome d'Abidjan",
    label: "Abidjan, Cote d'Ivoire",
    countryIso2: "CI",
    latitude: 5.298333,
    longitude: -4.016944,
    keywords: ["abidjan", "port", "autonome", "terminal", "vridi"],
  },
  {
    id: "airport-dla",
    kind: "AIRPORT",
    name: "Aeroport international de Douala",
    label: "Douala, Cameroun",
    countryIso2: "CM",
    latitude: 4.006081,
    longitude: 9.719481,
    keywords: ["douala", "airport", "aeroport", "dla"],
  },
  {
    id: "airport-nsi",
    kind: "AIRPORT",
    name: "Aeroport international de Yaounde-Nsimalen",
    label: "Yaounde, Cameroun",
    countryIso2: "CM",
    latitude: 3.7225,
    longitude: 11.5533,
    keywords: [
      "yaounde",
      "nsimalen",
      "airport",
      "aeroport",
      "nsi",
      "yaoundé",
      "nsimélen",
    ],
  },
  {
    id: "port-douala",
    kind: "PORT",
    name: "Port Autonome de Douala",
    label: "Douala, Cameroun",
    countryIso2: "CM",
    latitude: 4.042222,
    longitude: 9.678056,
    keywords: ["douala", "port", "autonome", "terminal"],
  },
  {
    id: "airport-bjz",
    kind: "AIRPORT",
    name: "Aeroport international de Brazzaville-Maya-Maya",
    label: "Brazzaville, Congo",
    countryIso2: "CG",
    latitude: -4.2517,
    longitude: 15.2533,
    keywords: ["brazzaville", "maya", "airport", "aeroport", "bjz"],
  },
  {
    id: "airport-fih",
    kind: "AIRPORT",
    name: "Aeroport international de Kinshasa-Ndjili",
    label: "Kinshasa, Republique Democratique du Congo",
    countryIso2: "CD",
    latitude: -4.3858,
    longitude: 15.4446,
    keywords: ["kinshasa", "ndjili", "airport", "aeroport", "fih"],
  },
  {
    id: "airport-los",
    kind: "AIRPORT",
    name: "Murtala Muhammed International Airport",
    label: "Lagos, Nigeria",
    countryIso2: "NG",
    latitude: 6.5774,
    longitude: 3.3211,
    keywords: ["lagos", "murtala", "muhammed", "airport", "aeroport", "los"],
  },
  {
    id: "airport-acc",
    kind: "AIRPORT",
    name: "Kotoka International Airport",
    label: "Accra, Ghana",
    countryIso2: "GH",
    latitude: 5.6052,
    longitude: -0.1668,
    keywords: ["accra", "kotoka", "airport", "aeroport", "acc"],
  },
  {
    id: "airport-dss",
    kind: "AIRPORT",
    name: "Aeroport international Blaise-Diagne",
    label: "Dakar, Senegal",
    countryIso2: "SN",
    latitude: 14.6711,
    longitude: -17.0733,
    keywords: ["dakar", "blaise", "diagne", "airport", "aeroport", "dss"],
  },
  {
    id: "airport-lfw",
    kind: "AIRPORT",
    name: "Aeroport international de Lome-Grissa",
    label: "Lome, Togo",
    countryIso2: "TG",
    latitude: 6.1657,
    longitude: 1.2541,
    keywords: ["lome", "grissa", "airport", "aeroport", "lfw"],
  },
  {
    id: "airport-coo",
    kind: "AIRPORT",
    name: "Aeroport international de Cotonou-Bernardin-Gantin",
    label: "Cotonou, Benin",
    countryIso2: "BJ",
    latitude: 6.3571,
    longitude: 2.3844,
    keywords: ["cotonou", "bernardin", "gantin", "airport", "aeroport", "coo"],
  },
  {
    id: "airport-oua",
    kind: "AIRPORT",
    name: "Aeroport international de Ouagadougou",
    label: "Ouagadougou, Burkina Faso",
    countryIso2: "BF",
    latitude: 12.3532,
    longitude: -1.5124,
    keywords: ["ouagadougou", "airport", "aeroport", "oua"],
  },
  {
    id: "airport-bko",
    kind: "AIRPORT",
    name: "Aeroport international Modibo-Keita",
    label: "Bamako, Mali",
    countryIso2: "ML",
    latitude: 12.5335,
    longitude: -7.9499,
    keywords: ["bamako", "modibo", "keita", "airport", "aeroport", "bko"],
  },
  {
    id: "airport-abv",
    kind: "AIRPORT",
    name: "Nnamdi Azikiwe International Airport",
    label: "Abuja, Nigeria",
    countryIso2: "NG",
    latitude: 9.0068,
    longitude: 7.2631,
    keywords: ["abuja", "nnamdi", "azikiwe", "airport", "aeroport", "abv"],
  },
  {
    id: "airport-nim",
    kind: "AIRPORT",
    name: "Aeroport international Diori-Hamani",
    label: "Niamey, Niger",
    countryIso2: "NE",
    latitude: 13.4818,
    longitude: 2.1836,
    keywords: ["niamey", "diori", "hamani", "airport", "aeroport", "nim"],
  },
  {
    id: "port-lagos",
    kind: "PORT",
    name: "Apapa Port Complex Lagos",
    label: "Lagos, Nigeria",
    countryIso2: "NG",
    latitude: 6.4333,
    longitude: 3.3833,
    keywords: ["lagos", "apapa", "port", "terminal", "nigeria"],
  },
  {
    id: "port-tema",
    kind: "PORT",
    name: "Port de Tema",
    label: "Tema, Ghana",
    countryIso2: "GH",
    latitude: 5.6333,
    longitude: -0.0167,
    keywords: ["tema", "port", "ghana", "terminal", "accra"],
  },
  {
    id: "port-dakar",
    kind: "PORT",
    name: "Port Autonome de Dakar",
    label: "Dakar, Senegal",
    countryIso2: "SN",
    latitude: 14.6833,
    longitude: -17.4333,
    keywords: ["dakar", "port", "senegal", "terminal"],
  },
  {
    id: "port-lome",
    kind: "PORT",
    name: "Port Autonome de Lome",
    label: "Lome, Togo",
    countryIso2: "TG",
    latitude: 6.1333,
    longitude: 1.2833,
    keywords: ["lome", "port", "togo", "terminal"],
  },
  {
    id: "port-cotonou",
    kind: "PORT",
    name: "Port Autonome de Cotonou",
    label: "Cotonou, Benin",
    countryIso2: "BJ",
    latitude: 6.35,
    longitude: 2.4333,
    keywords: ["cotonou", "port", "benin", "terminal"],
  },
  {
    id: "port-pointe-noire",
    kind: "PORT",
    name: "Port Autonome de Pointe-Noire",
    label: "Pointe-Noire, Congo",
    countryIso2: "CG",
    latitude: -4.7833,
    longitude: 11.85,
    keywords: ["pointe-noire", "port", "congo", "terminal"],
  },
  {
    id: "port-matadi",
    kind: "PORT",
    name: "Port de Matadi",
    label: "Matadi, Republique Democratique du Congo",
    countryIso2: "CD",
    latitude: -5.8167,
    longitude: 13.4667,
    keywords: ["matadi", "port", "rdc", "congo", "terminal"],
  },
  {
    id: "airport-pvg",
    kind: "AIRPORT",
    name: "Shanghai Pudong International Airport",
    label: "Shanghai, Chine",
    countryIso2: "CN",
    latitude: 31.144343,
    longitude: 121.808273,
    keywords: ["shanghai", "pudong", "airport", "pvg"],
  },
  {
    id: "airport-sha",
    kind: "AIRPORT",
    name: "Shanghai Hongqiao International Airport",
    label: "Shanghai, Chine",
    countryIso2: "CN",
    latitude: 31.197875,
    longitude: 121.336319,
    keywords: ["shanghai", "hongqiao", "airport", "sha"],
  },
  {
    id: "port-shanghai",
    kind: "PORT",
    name: "Port of Shanghai",
    label: "Shanghai, Chine",
    countryIso2: "CN",
    latitude: 31.230416,
    longitude: 121.473701,
    keywords: ["shanghai", "port", "yangshan", "container", "terminal"],
  },
  {
    id: "airport-can",
    kind: "AIRPORT",
    name: "Guangzhou Baiyun International Airport",
    label: "Guangzhou, Chine",
    countryIso2: "CN",
    latitude: 23.392436,
    longitude: 113.298786,
    keywords: ["guangzhou", "baiyun", "airport", "can"],
  },
  {
    id: "port-guangzhou",
    kind: "PORT",
    name: "Port of Guangzhou",
    label: "Guangzhou, Chine",
    countryIso2: "CN",
    latitude: 23.095,
    longitude: 113.454,
    keywords: ["guangzhou", "port", "nansha", "terminal"],
  },
  {
    id: "airport-szx",
    kind: "AIRPORT",
    name: "Shanghai Bao'an International Airport",
    label: "Shanghai, Chine",
    countryIso2: "CN",
    latitude: 22.639258,
    longitude: 113.810664,
    keywords: ["Shanghai", "baoan", "airport", "szx"],
  },
  {
    id: "port-Shanghai",
    kind: "PORT",
    name: "Port of Shanghai",
    label: "Shanghai, Chine",
    countryIso2: "CN",
    latitude: 22.543096,
    longitude: 114.057865,
    keywords: ["Shanghai", "port", "yantian", "shekou", "terminal"],
  },
  {
    id: "airport-cdg",
    kind: "AIRPORT",
    name: "Paris Charles de Gaulle Airport",
    label: "Paris, France",
    countryIso2: "FR",
    latitude: 49.00969,
    longitude: 2.547925,
    keywords: ["paris", "charles", "gaulle", "airport", "cdg"],
  },
  {
    id: "port-le-havre",
    kind: "PORT",
    name: "Port du Havre",
    label: "Le Havre, France",
    countryIso2: "FR",
    latitude: 49.4938,
    longitude: 0.1077,
    keywords: ["havre", "port", "france", "terminal"],
  },
  {
    id: "airport-jfk",
    kind: "AIRPORT",
    name: "John F. Kennedy International Airport",
    label: "New York, Etats-Unis",
    countryIso2: "US",
    latitude: 40.641311,
    longitude: -73.778139,
    keywords: ["new york", "jfk", "airport", "kennedy"],
  },
  {
    id: "port-new-york",
    kind: "PORT",
    name: "Port of New York and New Jersey",
    label: "New York, Etats-Unis",
    countryIso2: "US",
    latitude: 40.684,
    longitude: -74.006,
    keywords: ["new york", "new jersey", "port", "terminal"],
  },
];

export const AIRCRAFT_NAMES = [
  "Airbus A330 Cargo",
  "Airbus A350 Cargo",
  "Boeing 737 Freighter",
  "Boeing 747-8F",
  "Boeing 767 Freighter",
  "Boeing 777 Freighter",
  "Antonov An-124",
  "Vol cargo charter",
];

export const VESSEL_NAMES = [
  "Porte-conteneurs regional",
  "MSC cargo vessel",
  "CMA CGM cargo vessel",
  "Maersk container vessel",
  "COSCO container vessel",
  "Evergreen container vessel",
  "Navire roulier RoRo",
  "Navire cargo affrete",
];

export function searchTransportNodes(options: {
  query: string;
  kind: TransportNodeKind;
  countryIso2?: string | null;
  limit?: number;
}) {
  const query = options.query.trim().toLowerCase();
  const limit = options.limit ?? 12;
  return TRANSPORT_NODES.filter((node) => {
    if (node.kind !== options.kind) return false;
    if (
      options.countryIso2 &&
      node.countryIso2 !== options.countryIso2.toUpperCase()
    )
      return false;
    if (!query) return true;
    return `${node.name} ${node.label} ${node.keywords.join(" ")}`
      .toLowerCase()
      .includes(query);
  }).slice(0, limit);
}
