// Run: bun run prisma/seed-countries.ts
// Populates all countries from src/lib/countries.ts with continent + currency data.

import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("[seed-countries] DATABASE_URL is required");
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

// ISO2 → { continent, currencyCode, currencyName, currencySymbol, usdExchangeRate }
const COUNTRY_META: Record<string, { continent: string; currencyCode: string; currencyName: string; currencySymbol: string; usdExchangeRate: number }> = {
  AF: { continent: "Asia", currencyCode: "AFN", currencyName: "Afghani", currencySymbol: "؋", usdExchangeRate: 86 },
  ZA: { continent: "Africa", currencyCode: "ZAR", currencyName: "Rand", currencySymbol: "R", usdExchangeRate: 18.5 },
  AL: { continent: "Europe", currencyCode: "ALL", currencyName: "Lek", currencySymbol: "L", usdExchangeRate: 100 },
  DZ: { continent: "Africa", currencyCode: "DZD", currencyName: "Dinar", currencySymbol: "DA", usdExchangeRate: 135 },
  DE: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  AO: { continent: "Africa", currencyCode: "AOA", currencyName: "Kwanza", currencySymbol: "Kz", usdExchangeRate: 830 },
  SA: { continent: "Asia", currencyCode: "SAR", currencyName: "Riyal", currencySymbol: "﷼", usdExchangeRate: 3.75 },
  AR: { continent: "America", currencyCode: "ARS", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 1020 },
  AM: { continent: "Asia", currencyCode: "AMD", currencyName: "Dram", currencySymbol: "֏", usdExchangeRate: 390 },
  AU: { continent: "Oceania", currencyCode: "AUD", currencyName: "Dollar", currencySymbol: "A$", usdExchangeRate: 1.55 },
  AT: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  AZ: { continent: "Asia", currencyCode: "AZN", currencyName: "Manat", currencySymbol: "₼", usdExchangeRate: 1.7 },
  BS: { continent: "America", currencyCode: "BSD", currencyName: "Dollar", currencySymbol: "B$", usdExchangeRate: 1 },
  BH: { continent: "Asia", currencyCode: "BHD", currencyName: "Dinar", currencySymbol: ".د.ب", usdExchangeRate: 0.38 },
  BD: { continent: "Asia", currencyCode: "BDT", currencyName: "Taka", currencySymbol: "৳", usdExchangeRate: 110 },
  BB: { continent: "America", currencyCode: "BBD", currencyName: "Dollar", currencySymbol: "Bds$", usdExchangeRate: 2 },
  BE: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  BZ: { continent: "America", currencyCode: "BZD", currencyName: "Dollar", currencySymbol: "BZ$", usdExchangeRate: 2 },
  BJ: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  BT: { continent: "Asia", currencyCode: "BTN", currencyName: "Ngultrum", currencySymbol: "Nu.", usdExchangeRate: 83 },
  BY: { continent: "Europe", currencyCode: "BYN", currencyName: "Rouble", currencySymbol: "Br", usdExchangeRate: 3.2 },
  MM: { continent: "Asia", currencyCode: "MMK", currencyName: "Kyat", currencySymbol: "K", usdExchangeRate: 2100 },
  BO: { continent: "America", currencyCode: "BOB", currencyName: "Boliviano", currencySymbol: "Bs.", usdExchangeRate: 6.9 },
  BA: { continent: "Europe", currencyCode: "BAM", currencyName: "Mark", currencySymbol: "KM", usdExchangeRate: 1.8 },
  BW: { continent: "Africa", currencyCode: "BWP", currencyName: "Pula", currencySymbol: "P", usdExchangeRate: 13.5 },
  BR: { continent: "America", currencyCode: "BRL", currencyName: "Real", currencySymbol: "R$", usdExchangeRate: 5.2 },
  BN: { continent: "Asia", currencyCode: "BND", currencyName: "Dollar", currencySymbol: "B$", usdExchangeRate: 1.35 },
  BG: { continent: "Europe", currencyCode: "BGN", currencyName: "Lev", currencySymbol: "лв", usdExchangeRate: 1.8 },
  BF: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  BI: { continent: "Africa", currencyCode: "BIF", currencyName: "Franc", currencySymbol: "FBu", usdExchangeRate: 2850 },
  KH: { continent: "Asia", currencyCode: "KHR", currencyName: "Riel", currencySymbol: "៛", usdExchangeRate: 4100 },
  CM: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  CA: { continent: "America", currencyCode: "CAD", currencyName: "Dollar", currencySymbol: "C$", usdExchangeRate: 1.38 },
  CV: { continent: "Africa", currencyCode: "CVE", currencyName: "Escudo", currencySymbol: "$", usdExchangeRate: 100 },
  CF: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  CL: { continent: "America", currencyCode: "CLP", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 930 },
  CN: { continent: "Asia", currencyCode: "CNY", currencyName: "Yuan", currencySymbol: "¥", usdExchangeRate: 7.2 },
  CY: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  CO: { continent: "America", currencyCode: "COP", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 4200 },
  KM: { continent: "Africa", currencyCode: "KMF", currencyName: "Franc", currencySymbol: "CF", usdExchangeRate: 460 },
  CG: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  CD: { continent: "Africa", currencyCode: "CDF", currencyName: "Franc", currencySymbol: "FC", usdExchangeRate: 2850 },
  KR: { continent: "Asia", currencyCode: "KRW", currencyName: "Won", currencySymbol: "₩", usdExchangeRate: 1350 },
  CR: { continent: "America", currencyCode: "CRC", currencyName: "Colon", currencySymbol: "₡", usdExchangeRate: 530 },
  HR: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  CU: { continent: "America", currencyCode: "CUP", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 24 },
  DK: { continent: "Europe", currencyCode: "DKK", currencyName: "Couronne", currencySymbol: "kr", usdExchangeRate: 6.9 },
  DJ: { continent: "Africa", currencyCode: "DJF", currencyName: "Franc", currencySymbol: "Fdj", usdExchangeRate: 178 },
  DO: { continent: "America", currencyCode: "DOP", currencyName: "Peso", currencySymbol: "RD$", usdExchangeRate: 58 },
  EG: { continent: "Africa", currencyCode: "EGP", currencyName: "Livre", currencySymbol: "£", usdExchangeRate: 48 },
  AE: { continent: "Asia", currencyCode: "AED", currencyName: "Dirham", currencySymbol: "د.إ", usdExchangeRate: 3.67 },
  EC: { continent: "America", currencyCode: "USD", currencyName: "Dollar", currencySymbol: "$", usdExchangeRate: 1 },
  ER: { continent: "Africa", currencyCode: "ERN", currencyName: "Nakfa", currencySymbol: "Nfk", usdExchangeRate: 15 },
  ES: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  EE: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  SZ: { continent: "Africa", currencyCode: "SZL", currencyName: "Lilangeni", currencySymbol: "E", usdExchangeRate: 18.5 },
  US: { continent: "America", currencyCode: "USD", currencyName: "Dollar", currencySymbol: "$", usdExchangeRate: 1 },
  ET: { continent: "Africa", currencyCode: "ETB", currencyName: "Birr", currencySymbol: "Br", usdExchangeRate: 55 },
  FJ: { continent: "Oceania", currencyCode: "FJD", currencyName: "Dollar", currencySymbol: "FJ$", usdExchangeRate: 2.2 },
  FI: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  FR: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  GA: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  GM: { continent: "Africa", currencyCode: "GMD", currencyName: "Dalasi", currencySymbol: "D", usdExchangeRate: 65 },
  GE: { continent: "Asia", currencyCode: "GEL", currencyName: "Lari", currencySymbol: "₾", usdExchangeRate: 2.8 },
  GH: { continent: "Africa", currencyCode: "GHS", currencyName: "Cedi", currencySymbol: "GH₵", usdExchangeRate: 15.2 },
  GR: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  GN: { continent: "Africa", currencyCode: "GNF", currencyName: "Franc", currencySymbol: "FG", usdExchangeRate: 8500 },
  GQ: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  GW: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  HT: { continent: "America", currencyCode: "HTG", currencyName: "Gourde", currencySymbol: "G", usdExchangeRate: 135 },
  HN: { continent: "America", currencyCode: "HNL", currencyName: "Lempira", currencySymbol: "L", usdExchangeRate: 25 },
  HU: { continent: "Europe", currencyCode: "HUF", currencyName: "Forint", currencySymbol: "Ft", usdExchangeRate: 380 },
  IN: { continent: "Asia", currencyCode: "INR", currencyName: "Roupie", currencySymbol: "₹", usdExchangeRate: 83 },
  ID: { continent: "Asia", currencyCode: "IDR", currencyName: "Rupiah", currencySymbol: "Rp", usdExchangeRate: 15800 },
  IQ: { continent: "Asia", currencyCode: "IQD", currencyName: "Dinar", currencySymbol: "ع.د", usdExchangeRate: 1310 },
  IR: { continent: "Asia", currencyCode: "IRR", currencyName: "Rial", currencySymbol: "﷼", usdExchangeRate: 42000 },
  IE: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  IS: { continent: "Europe", currencyCode: "ISK", currencyName: "Couronne", currencySymbol: "kr", usdExchangeRate: 140 },
  IL: { continent: "Asia", currencyCode: "ILS", currencyName: "Shekel", currencySymbol: "₪", usdExchangeRate: 3.7 },
  IT: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  JM: { continent: "America", currencyCode: "JMD", currencyName: "Dollar", currencySymbol: "J$", usdExchangeRate: 155 },
  JP: { continent: "Asia", currencyCode: "JPY", currencyName: "Yen", currencySymbol: "¥", usdExchangeRate: 150 },
  JO: { continent: "Asia", currencyCode: "JOD", currencyName: "Dinar", currencySymbol: "د.ا", usdExchangeRate: 0.71 },
  KZ: { continent: "Asia", currencyCode: "KZT", currencyName: "Tenge", currencySymbol: "₸", usdExchangeRate: 460 },
  KE: { continent: "Africa", currencyCode: "KES", currencyName: "Shilling", currencySymbol: "KSh", usdExchangeRate: 145 },
  KG: { continent: "Asia", currencyCode: "KGS", currencyName: "Som", currencySymbol: "с", usdExchangeRate: 89 },
  KW: { continent: "Asia", currencyCode: "KWD", currencyName: "Dinar", currencySymbol: "د.ك", usdExchangeRate: 0.31 },
  LA: { continent: "Asia", currencyCode: "LAK", currencyName: "Kip", currencySymbol: "₭", usdExchangeRate: 21000 },
  LS: { continent: "Africa", currencyCode: "LSL", currencyName: "Loti", currencySymbol: "L", usdExchangeRate: 18.5 },
  LV: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  LB: { continent: "Asia", currencyCode: "LBP", currencyName: "Livre", currencySymbol: "ل.ل", usdExchangeRate: 89000 },
  LR: { continent: "Africa", currencyCode: "LRD", currencyName: "Dollar", currencySymbol: "L$", usdExchangeRate: 190 },
  LY: { continent: "Africa", currencyCode: "LYD", currencyName: "Dinar", currencySymbol: "ل.د", usdExchangeRate: 4.8 },
  LT: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  LU: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  MG: { continent: "Africa", currencyCode: "MGA", currencyName: "Ariary", currencySymbol: "Ar", usdExchangeRate: 4500 },
  MY: { continent: "Asia", currencyCode: "MYR", currencyName: "Ringgit", currencySymbol: "RM", usdExchangeRate: 4.7 },
  MW: { continent: "Africa", currencyCode: "MWK", currencyName: "Kwacha", currencySymbol: "MK", usdExchangeRate: 1700 },
  MV: { continent: "Asia", currencyCode: "MVR", currencyName: "Rufiyaa", currencySymbol: "Rf", usdExchangeRate: 15.4 },
  ML: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  MT: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  MA: { continent: "Africa", currencyCode: "MAD", currencyName: "Dirham", currencySymbol: "DH", usdExchangeRate: 10.1 },
  MR: { continent: "Africa", currencyCode: "MRU", currencyName: "Ouguiya", currencySymbol: "UM", usdExchangeRate: 38 },
  MU: { continent: "Africa", currencyCode: "MUR", currencyName: "Roupie", currencySymbol: "Rs", usdExchangeRate: 45 },
  MX: { continent: "America", currencyCode: "MXN", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 17.5 },
  MD: { continent: "Europe", currencyCode: "MDL", currencyName: "Leu", currencySymbol: "L", usdExchangeRate: 18 },
  MN: { continent: "Asia", currencyCode: "MNT", currencyName: "Tugrik", currencySymbol: "₮", usdExchangeRate: 3400 },
  ME: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  MZ: { continent: "Africa", currencyCode: "MZN", currencyName: "Metical", currencySymbol: "MT", usdExchangeRate: 63 },
  NA: { continent: "Africa", currencyCode: "NAD", currencyName: "Dollar", currencySymbol: "N$", usdExchangeRate: 18.5 },
  NP: { continent: "Asia", currencyCode: "NPR", currencyName: "Roupie", currencySymbol: "Rs", usdExchangeRate: 133 },
  NI: { continent: "America", currencyCode: "NIO", currencyName: "Cordoba", currencySymbol: "C$", usdExchangeRate: 36 },
  NE: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  NG: { continent: "Africa", currencyCode: "NGN", currencyName: "Naira", currencySymbol: "₦", usdExchangeRate: 1450 },
  NO: { continent: "Europe", currencyCode: "NOK", currencyName: "Couronne", currencySymbol: "kr", usdExchangeRate: 10.8 },
  NZ: { continent: "Oceania", currencyCode: "NZD", currencyName: "Dollar", currencySymbol: "NZ$", usdExchangeRate: 1.65 },
  OM: { continent: "Asia", currencyCode: "OMR", currencyName: "Rial", currencySymbol: "﷼", usdExchangeRate: 0.38 },
  UG: { continent: "Africa", currencyCode: "UGX", currencyName: "Shilling", currencySymbol: "USh", usdExchangeRate: 3750 },
  UZ: { continent: "Asia", currencyCode: "UZS", currencyName: "Som", currencySymbol: "с", usdExchangeRate: 12500 },
  PK: { continent: "Asia", currencyCode: "PKR", currencyName: "Roupie", currencySymbol: "Rs", usdExchangeRate: 280 },
  PA: { continent: "America", currencyCode: "PAB", currencyName: "Balboa", currencySymbol: "B/.", usdExchangeRate: 1 },
  PG: { continent: "Oceania", currencyCode: "PGK", currencyName: "Kina", currencySymbol: "K", usdExchangeRate: 3.8 },
  PY: { continent: "America", currencyCode: "PYG", currencyName: "Guarani", currencySymbol: "₲", usdExchangeRate: 7500 },
  NL: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  PH: { continent: "Asia", currencyCode: "PHP", currencyName: "Peso", currencySymbol: "₱", usdExchangeRate: 56 },
  PL: { continent: "Europe", currencyCode: "PLN", currencyName: "Zloty", currencySymbol: "zł", usdExchangeRate: 4.1 },
  PT: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  QA: { continent: "Asia", currencyCode: "QAR", currencyName: "Riyal", currencySymbol: "﷼", usdExchangeRate: 3.64 },
  RO: { continent: "Europe", currencyCode: "RON", currencyName: "Leu", currencySymbol: "lei", usdExchangeRate: 4.6 },
  GB: { continent: "Europe", currencyCode: "GBP", currencyName: "Livre", currencySymbol: "£", usdExchangeRate: 0.8 },
  RU: { continent: "Europe", currencyCode: "RUB", currencyName: "Rouble", currencySymbol: "₽", usdExchangeRate: 90 },
  RW: { continent: "Africa", currencyCode: "RWF", currencyName: "Franc", currencySymbol: "FRw", usdExchangeRate: 1300 },
  SN: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  RS: { continent: "Europe", currencyCode: "RSD", currencyName: "Dinar", currencySymbol: "дин", usdExchangeRate: 110 },
  SC: { continent: "Africa", currencyCode: "SCR", currencyName: "Roupie", currencySymbol: "Rs", usdExchangeRate: 14 },
  SL: { continent: "Africa", currencyCode: "SLL", currencyName: "Leone", currencySymbol: "Le", usdExchangeRate: 22000 },
  SG: { continent: "Asia", currencyCode: "SGD", currencyName: "Dollar", currencySymbol: "S$", usdExchangeRate: 1.35 },
  SK: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  SI: { continent: "Europe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€", usdExchangeRate: 0.92 },
  SO: { continent: "Africa", currencyCode: "SOS", currencyName: "Shilling", currencySymbol: "Sh", usdExchangeRate: 570 },
  SD: { continent: "Africa", currencyCode: "SDG", currencyName: "Livre", currencySymbol: "£", usdExchangeRate: 600 },
  SS: { continent: "Africa", currencyCode: "SSP", currencyName: "Livre", currencySymbol: "£", usdExchangeRate: 800 },
  LK: { continent: "Asia", currencyCode: "LKR", currencyName: "Roupie", currencySymbol: "Rs", usdExchangeRate: 310 },
  SE: { continent: "Europe", currencyCode: "SEK", currencyName: "Couronne", currencySymbol: "kr", usdExchangeRate: 10.5 },
  CH: { continent: "Europe", currencyCode: "CHF", currencyName: "Franc", currencySymbol: "Fr", usdExchangeRate: 0.9 },
  SR: { continent: "America", currencyCode: "SRD", currencyName: "Dollar", currencySymbol: "$", usdExchangeRate: 35 },
  SY: { continent: "Asia", currencyCode: "SYP", currencyName: "Livre", currencySymbol: "£", usdExchangeRate: 13000 },
  TJ: { continent: "Asia", currencyCode: "TJS", currencyName: "Somoni", currencySymbol: "ЅМ", usdExchangeRate: 11 },
  TZ: { continent: "Africa", currencyCode: "TZS", currencyName: "Shilling", currencySymbol: "TSh", usdExchangeRate: 2550 },
  TD: { continent: "Africa", currencyCode: "XAF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  CZ: { continent: "Europe", currencyCode: "CZK", currencyName: "Couronne", currencySymbol: "Kč", usdExchangeRate: 23 },
  TH: { continent: "Asia", currencyCode: "THB", currencyName: "Baht", currencySymbol: "฿", usdExchangeRate: 36 },
  TL: { continent: "Asia", currencyCode: "USD", currencyName: "Dollar", currencySymbol: "$", usdExchangeRate: 1 },
  TG: { continent: "Africa", currencyCode: "XOF", currencyName: "Franc CFA", currencySymbol: "F CFA", usdExchangeRate: 605 },
  TN: { continent: "Africa", currencyCode: "TND", currencyName: "Dinar", currencySymbol: "د.ت", usdExchangeRate: 3.1 },
  TM: { continent: "Asia", currencyCode: "TMT", currencyName: "Manat", currencySymbol: "m", usdExchangeRate: 3.5 },
  TR: { continent: "Asia", currencyCode: "TRY", currencyName: "Lire", currencySymbol: "₺", usdExchangeRate: 30 },
  UA: { continent: "Europe", currencyCode: "UAH", currencyName: "Hryvnia", currencySymbol: "₴", usdExchangeRate: 40 },
  UY: { continent: "America", currencyCode: "UYU", currencyName: "Peso", currencySymbol: "$", usdExchangeRate: 39 },
  VU: { continent: "Oceania", currencyCode: "VUV", currencyName: "Vatu", currencySymbol: "VT", usdExchangeRate: 120 },
  VE: { continent: "America", currencyCode: "VES", currencyName: "Bolivar", currencySymbol: "Bs", usdExchangeRate: 36 },
  VN: { continent: "Asia", currencyCode: "VND", currencyName: "Dong", currencySymbol: "₫", usdExchangeRate: 25000 },
  YE: { continent: "Asia", currencyCode: "YER", currencyName: "Rial", currencySymbol: "﷼", usdExchangeRate: 250 },
  ZM: { continent: "Africa", currencyCode: "ZMW", currencyName: "Kwacha", currencySymbol: "ZK", usdExchangeRate: 25 },
  ZW: { continent: "Africa", currencyCode: "ZWL", currencyName: "Dollar", currencySymbol: "Z$", usdExchangeRate: 320 },
  MK: { continent: "Europe", currencyCode: "MKD", currencyName: "Denar", currencySymbol: "ден", usdExchangeRate: 58 },
  // Additional territories
  EH: { continent: "Africa", currencyCode: "MAD", currencyName: "Dirham", currencySymbol: "DH", usdExchangeRate: 10.1 },
};

// Countries from src/lib/countries.ts
const COUNTRY_NAMES = [
  { name: "Afghanistan", code: "AF", dialCode: "+93" },
  { name: "Afrique du Sud", code: "ZA", dialCode: "+27" },
  { name: "Albanie", code: "AL", dialCode: "+355" },
  { name: "Algérie", code: "DZ", dialCode: "+213" },
  { name: "Allemagne", code: "DE", dialCode: "+49" },
  { name: "Angola", code: "AO", dialCode: "+244" },
  { name: "Arabie saoudite", code: "SA", dialCode: "+966" },
  { name: "Argentine", code: "AR", dialCode: "+54" },
  { name: "Arménie", code: "AM", dialCode: "+374" },
  { name: "Australie", code: "AU", dialCode: "+61" },
  { name: "Autriche", code: "AT", dialCode: "+43" },
  { name: "Azerbaïdjan", code: "AZ", dialCode: "+994" },
  { name: "Bahamas", code: "BS", dialCode: "+1-242" },
  { name: "Bahreïn", code: "BH", dialCode: "+973" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Barbade", code: "BB", dialCode: "+1-246" },
  { name: "Belgique", code: "BE", dialCode: "+32" },
  { name: "Belize", code: "BZ", dialCode: "+501" },
  { name: "Bénin", code: "BJ", dialCode: "+229" },
  { name: "Bhoutan", code: "BT", dialCode: "+975" },
  { name: "Biélorussie", code: "BY", dialCode: "+375" },
  { name: "Birmanie", code: "MM", dialCode: "+95" },
  { name: "Bolivie", code: "BO", dialCode: "+591" },
  { name: "Bosnie", code: "BA", dialCode: "+387" },
  { name: "Botswana", code: "BW", dialCode: "+267" },
  { name: "Brésil", code: "BR", dialCode: "+55" },
  { name: "Brunei", code: "BN", dialCode: "+673" },
  { name: "Bulgarie", code: "BG", dialCode: "+359" },
  { name: "Burkina Faso", code: "BF", dialCode: "+226" },
  { name: "Burundi", code: "BI", dialCode: "+257" },
  { name: "Cambodge", code: "KH", dialCode: "+855" },
  { name: "Cameroun", code: "CM", dialCode: "+237" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Cap-Vert", code: "CV", dialCode: "+238" },
  { name: "République centrafricaine", code: "CF", dialCode: "+236" },
  { name: "Chili", code: "CL", dialCode: "+56" },
  { name: "Chine", code: "CN", dialCode: "+86" },
  { name: "Chypre", code: "CY", dialCode: "+357" },
  { name: "Colombie", code: "CO", dialCode: "+57" },
  { name: "Comores", code: "KM", dialCode: "+269" },
  { name: "Congo", code: "CG", dialCode: "+242" },
  { name: "République démocratique du Congo", code: "CD", dialCode: "+243" },
  { name: "Corée du Sud", code: "KR", dialCode: "+82" },
  { name: "Costa Rica", code: "CR", dialCode: "+506" },
  { name: "Croatie", code: "HR", dialCode: "+385" },
  { name: "Cuba", code: "CU", dialCode: "+53" },
  { name: "Danemark", code: "DK", dialCode: "+45" },
  { name: "Djibouti", code: "DJ", dialCode: "+253" },
  { name: "République dominicaine", code: "DO", dialCode: "+1-809" },
  { name: "Égypte", code: "EG", dialCode: "+20" },
  { name: "Émirats arabes unis", code: "AE", dialCode: "+971" },
  { name: "Équateur", code: "EC", dialCode: "+593" },
  { name: "Érythrée", code: "ER", dialCode: "+291" },
  { name: "Espagne", code: "ES", dialCode: "+34" },
  { name: "Estonie", code: "EE", dialCode: "+372" },
  { name: "Eswatini", code: "SZ", dialCode: "+268" },
  { name: "États-Unis", code: "US", dialCode: "+1" },
  { name: "Éthiopie", code: "ET", dialCode: "+251" },
  { name: "Fidji", code: "FJ", dialCode: "+679" },
  { name: "Finlande", code: "FI", dialCode: "+358" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "Gabon", code: "GA", dialCode: "+241" },
  { name: "Gambie", code: "GM", dialCode: "+220" },
  { name: "Géorgie", code: "GE", dialCode: "+995" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "Grèce", code: "GR", dialCode: "+30" },
  { name: "Guinée", code: "GN", dialCode: "+224" },
  { name: "Guinée équatoriale", code: "GQ", dialCode: "+240" },
  { name: "Guinée-Bissau", code: "GW", dialCode: "+245" },
  { name: "Haïti", code: "HT", dialCode: "+509" },
  { name: "Honduras", code: "HN", dialCode: "+504" },
  { name: "Hongrie", code: "HU", dialCode: "+36" },
  { name: "Inde", code: "IN", dialCode: "+91" },
  { name: "Indonésie", code: "ID", dialCode: "+62" },
  { name: "Irak", code: "IQ", dialCode: "+964" },
  { name: "Iran", code: "IR", dialCode: "+98" },
  { name: "Irlande", code: "IE", dialCode: "+353" },
  { name: "Islande", code: "IS", dialCode: "+354" },
  { name: "Israël", code: "IL", dialCode: "+972" },
  { name: "Italie", code: "IT", dialCode: "+39" },
  { name: "Jamaïque", code: "JM", dialCode: "+1-876" },
  { name: "Japon", code: "JP", dialCode: "+81" },
  { name: "Jordanie", code: "JO", dialCode: "+962" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "Kirghizistan", code: "KG", dialCode: "+996" },
  { name: "Koweït", code: "KW", dialCode: "+965" },
  { name: "Laos", code: "LA", dialCode: "+856" },
  { name: "Lesotho", code: "LS", dialCode: "+266" },
  { name: "Lettonie", code: "LV", dialCode: "+371" },
  { name: "Liban", code: "LB", dialCode: "+961" },
  { name: "Libéria", code: "LR", dialCode: "+231" },
  { name: "Libye", code: "LY", dialCode: "+218" },
  { name: "Lituanie", code: "LT", dialCode: "+370" },
  { name: "Luxembourg", code: "LU", dialCode: "+352" },
  { name: "Madagascar", code: "MG", dialCode: "+261" },
  { name: "Malaisie", code: "MY", dialCode: "+60" },
  { name: "Malawi", code: "MW", dialCode: "+265" },
  { name: "Maldives", code: "MV", dialCode: "+960" },
  { name: "Mali", code: "ML", dialCode: "+223" },
  { name: "Malte", code: "MT", dialCode: "+356" },
  { name: "Maroc", code: "MA", dialCode: "+212" },
  { name: "Mauritanie", code: "MR", dialCode: "+222" },
  { name: "Maurice", code: "MU", dialCode: "+230" },
  { name: "Mexique", code: "MX", dialCode: "+52" },
  { name: "Moldavie", code: "MD", dialCode: "+373" },
  { name: "Mongolie", code: "MN", dialCode: "+976" },
  { name: "Monténégro", code: "ME", dialCode: "+382" },
  { name: "Mozambique", code: "MZ", dialCode: "+258" },
  { name: "Namibie", code: "NA", dialCode: "+264" },
  { name: "Népal", code: "NP", dialCode: "+977" },
  { name: "Nicaragua", code: "NI", dialCode: "+505" },
  { name: "Niger", code: "NE", dialCode: "+227" },
  { name: "Nigéria", code: "NG", dialCode: "+234" },
  { name: "Norvège", code: "NO", dialCode: "+47" },
  { name: "Nouvelle-Zélande", code: "NZ", dialCode: "+64" },
  { name: "Oman", code: "OM", dialCode: "+968" },
  { name: "Ouganda", code: "UG", dialCode: "+256" },
  { name: "Ouzbékistan", code: "UZ", dialCode: "+998" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Panama", code: "PA", dialCode: "+507" },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", dialCode: "+675" },
  { name: "Paraguay", code: "PY", dialCode: "+595" },
  { name: "Pays-Bas", code: "NL", dialCode: "+31" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "Pologne", code: "PL", dialCode: "+48" },
  { name: "Portugal", code: "PT", dialCode: "+351" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Roumanie", code: "RO", dialCode: "+40" },
  { name: "Royaume-Uni", code: "GB", dialCode: "+44" },
  { name: "Russie", code: "RU", dialCode: "+7" },
  { name: "Rwanda", code: "RW", dialCode: "+250" },
  { name: "Sénégal", code: "SN", dialCode: "+221" },
  { name: "Serbie", code: "RS", dialCode: "+381" },
  { name: "Seychelles", code: "SC", dialCode: "+248" },
  { name: "Sierra Leone", code: "SL", dialCode: "+232" },
  { name: "Singapour", code: "SG", dialCode: "+65" },
  { name: "Slovaquie", code: "SK", dialCode: "+421" },
  { name: "Slovénie", code: "SI", dialCode: "+386" },
  { name: "Somalie", code: "SO", dialCode: "+252" },
  { name: "Soudan", code: "SD", dialCode: "+249" },
  { name: "Soudan du Sud", code: "SS", dialCode: "+211" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94" },
  { name: "Suède", code: "SE", dialCode: "+46" },
  { name: "Suisse", code: "CH", dialCode: "+41" },
  { name: "Suriname", code: "SR", dialCode: "+597" },
  { name: "Syrie", code: "SY", dialCode: "+963" },
  { name: "Tadjikistan", code: "TJ", dialCode: "+992" },
  { name: "Tanzanie", code: "TZ", dialCode: "+255" },
  { name: "Tchad", code: "TD", dialCode: "+235" },
  { name: "République tchèque", code: "CZ", dialCode: "+420" },
  { name: "Thaïlande", code: "TH", dialCode: "+66" },
  { name: "Timor oriental", code: "TL", dialCode: "+670" },
  { name: "Togo", code: "TG", dialCode: "+228" },
  { name: "Tunisie", code: "TN", dialCode: "+216" },
  { name: "Turkménistan", code: "TM", dialCode: "+993" },
  { name: "Turquie", code: "TR", dialCode: "+90" },
  { name: "Ukraine", code: "UA", dialCode: "+380" },
  { name: "Uruguay", code: "UY", dialCode: "+598" },
  { name: "Vanuatu", code: "VU", dialCode: "+678" },
  { name: "Venezuela", code: "VE", dialCode: "+58" },
  { name: "Viêt Nam", code: "VN", dialCode: "+84" },
  { name: "Yémen", code: "YE", dialCode: "+967" },
  { name: "Zambie", code: "ZM", dialCode: "+260" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263" },
  // Extra
  { name: "Côte d'Ivoire", code: "CI", dialCode: "+225" },
  { name: "Macédoine du Nord", code: "MK", dialCode: "+389" },
];

async function main() {
  console.log("[seed-countries] Starting...");

  for (const c of COUNTRY_NAMES) {
    const meta = COUNTRY_META[c.code];
    if (!meta) {
      console.warn(`[seed-countries] No metadata for ${c.name} (${c.code}), skipping`);
      continue;
    }
    const slug = c.name
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/^-+|-+$/g, "")
      .substring(0, 200);

    try {
      await prisma.country.upsert({
        where: { iso2: c.code },
        update: {
          name: c.name,
          dialingCode: c.dialCode,
          continent: meta.continent,
          currencyCode: meta.currencyCode,
          currencyName: meta.currencyName,
          currencySymbol: meta.currencySymbol,
          usdExchangeRate: meta.usdExchangeRate,
          isFeatured: meta.continent === "Africa" && ["CI", "SN", "ML", "NG", "GH", "CM", "BJ", "TG", "CD", "MA", "KE", "ZA", "DZ", "TN"].includes(c.code),
        },
        create: {
          name: c.name,
          slug,
          iso2: c.code,
          dialingCode: c.dialCode,
          continent: meta.continent,
          currencyCode: meta.currencyCode,
          currencyName: meta.currencyName,
          currencySymbol: meta.currencySymbol,
          usdExchangeRate: meta.usdExchangeRate,
          isFeatured: meta.continent === "Africa" && ["CI", "SN", "ML", "NG", "GH", "CM", "BJ", "TG", "CD", "MA", "KE", "ZA", "DZ", "TN"].includes(c.code),
        },
      });
    } catch (err) {
      console.error(`[seed-countries] Error for ${c.name} (${c.code}):`, String(err));
    }
  }

  const count = await prisma.country.count();
  console.log(`[seed-countries] Done. ${count} countries in database.`);
  await prisma.$disconnect();
}

main();
